---
- name: Create dir
  ansible.builtin.file:
    path: /opt/postgres/backup
    state: directory

- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/postgres/docker-compose.yml

- name: Copy backup
  ansible.builtin.template:
    src: backup.sql.j2
    dest: /opt/postgres/backup/backup.sql

- name: Copy env
  ansible.builtin.template:
    src: env.j2
    dest: /opt/postgres/.env
    mode: 0600

- name: deploy docker
  shell: docker compose -f /opt/postgres/docker-compose.yml up -d

- name: Restore db
  command: >
    docker exec postgres
    /bin/sh -c "psql -U {{ db_user }} -d {{ db_name }} < /data/backup.sql"
